# Generated by Django 6.0.2 on 2026-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to='profiles/'),
        ),
    ]
