# Generated by Django 6.0.2 on 2026-03-27 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be at least 2 characters long')])),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0, 'Price per day can`t be less than 0.')])),
                ('image_url', models.URLField(blank=True, help_text='Image URL', null=True)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Tools', 'Tools'), ('Vehicles', 'Vehicles'), ('Party Equipment', 'Party Equipment')], default='Tools', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
