# Generated by Django 6.0.2 on 2026-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file.', null=True, upload_to='items/'),
        ),
    ]
