# Generated by Django 6.0.2 on 2026-02-21 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Customer name must be at least 2 characters long')])),
                ('customer_email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('items', models.ManyToManyField(related_name='reservations', to='catalog.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
